name: Update Trello Card on PR Events

on:
  pull_request:
    types: [opened, closed]

jobs:
  update-trello-card:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Issue Number from PR Body
        id: extract
        run: |
          echo "Extracting issue number from PR body..."
          BODY="${{ github.event.pull_request.body }}"
          ISSUE_NUMBER=$(echo "$BODY" | grep -oE "#[0-9]+" | head -n1 | tr -d '#')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Skip if No Issue Number Found
        if: steps.extract.outputs.ISSUE_NUMBER == ''
        run: echo "No issue number found in PR body. Skipping workflow..."

      - name: Add PR Link as Comment to Trello Card
        if: github.event.action == 'opened' && steps.extract.outputs.ISSUE_NUMBER != ''
        run: |
          curl --request POST \
            --url "https://api.trello.com/1/cards/${{ steps.extract.outputs.ISSUE_NUMBER }}/actions/comments" \
            --header "Content-Type: application/json" \
            --data '{
              "text": "PR opened: '${{ github.event.pull_request.html_url }}'",
              "key": "'"${{ secrets.TRELLO_KEY }}"'",
              "token": "'"${{ secrets.TRELLO_TOKEN }}"'"
            }'

      - name: Update Card with Done Label & Complete
        if: github.event.action == 'closed' && github.event.pull_request.merged == true && steps.extract.outputs.ISSUE_NUMBER != ''
        run: |
          # Add 'Done (PR Merged)' label
          curl --request POST \
            --url "https://api.trello.com/1/cards/${{ steps.extract.outputs.ISSUE_NUMBER }}/idLabels" \
            --header "Content-Type: application/json" \
            --data '{
              "value": "'"${{ secrets.TRELLO_DONE_LABEL_ID }}"'",
              "key": "'"${{ secrets.TRELLO_KEY }}"'",
              "token": "'"${{ secrets.TRELLO_TOKEN }}"'"
            }'

          # Set dueComplete to true
          curl --request PUT \
            --url "https://api.trello.com/1/cards/${{ steps.extract.outputs.ISSUE_NUMBER }}" \
            --header "Content-Type: application/json" \
            --data '{
              "dueComplete": true,
              "key": "'"${{ secrets.TRELLO_KEY }}"'",
              "token": "'"${{ secrets.TRELLO_TOKEN }}"'"
            }'
